# Generated by Django 2.0.2 on 2018-03-10 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationInfo',
            fields=[
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('father_name', models.CharField(max_length=128)),
                ('date_of_birth', models.DateField(max_length=40)),
                ('roll_num', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('phone', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=250)),
                ('education', models.CharField(max_length=200)),
            ],
        ),
    ]
