# Generated by Django 2.0.2 on 2018-03-10 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_admins'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admins',
        ),
    ]
