# Generated by Django 2.0.2 on 2018-03-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_admins'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationinfo',
            name='uid',
            field=models.CharField(default=1, max_length=250),
        ),
    ]
