# Generated by Django 2.0.2 on 2018-03-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20180310_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationinfo',
            name='roll_num',
            field=models.IntegerField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
