# Generated by Django 2.0.2 on 2018-03-14 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20180310_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationinfo',
            name='roll_num',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
