# Generated by Django 2.0.2 on 2018-03-14 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20180314_0406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationinfo',
            name='roll_num',
            field=models.CharField(max_length=40, primary_key=True, serialize=False, unique=True),
        ),
    ]
